---
- name: get php version
  shell: php -v | grep ^PHP | awk '{print $2}'| awk -F. '{print $1 "." $2}'
  register: php_version

- name: Create ioncube library directory
  file: path=/usr/lib/ioncube state=directory

- name: Install ioncube 
  copy: src="{{role_path}}/files/ioncube_loader_lin_{{php_version.stdout}}.so"  dest="/usr/lib/ioncube/"
  notify:
    - restart apache

- include: tasks/debian.yml
  when: ansible_os_family == "Debian"

- include: tasks/redhat.yml
  when: ansible_os_family == "RedHat"

