---
- name: get php version
  shell: php -v | grep ^PHP | awk '{print $2}'| awk -F. '{print $1 "." $2}'
  register: php_version

- name: Create ioncube library directory
  file: path=/usr/lib/ioncube state=directory

- name: Install ioncube 
  copy: src="{{role_path}}/files/ioncube_loader_lin_{{php_version.stdout}}.so"  dest="/usr/lib/ioncube/"
  notify:
    - restart apache

- stat: path=/etc/php
  register: php_install

- name: Install ioncube php apache2 config
  when: php_install.stat.isdir == true
  template: src="{{role_path}}/templates/05-ioncube.ini" dest="/etc/php/{{php_version.stdout}}/apache2/conf.d/" 
  notify:
    - restart apache

- name: Install ioncube php cli config
  when: php_install.stat.isdir == true
  template: src="{{role_path}}/templates/05-ioncube.ini" dest="/etc/php/{{php_version.stdout}}/cli/conf.d/" 
  notify:
    - restart apache

- stat: path=/etc/php5
  register: php5_install

- name: Install ioncube php apache2 config alt path
  when: php_install.stat.isdir == true
  template: src="{{role_path}}/templates/05-ioncube.ini" dest="/etc/php5/apache2/conf.d/" 
  notify:
    - restart apache

- name: Install ioncube php cli config alt path
  when: php_install.stat.isdir == true
  template: src="{{role_path}}/templates/05-ioncube.ini" dest="/etc/php5/cli/conf.d/" 
  notify:
    - restart apache

